### ISSUE TITLE
Don't use px for dynamic properties

### ISSUE THREAD

**Issue by joostf** [r20222/fix-the-flow-interactive-website#8]
https://github.com/r20222/fix-the-flow-interactive-website/blob/238e993df137c15be52c86f9b1d1f098e6d07937/styles/style.css#L26-L28

**Comment by r20222** [comment]
@joostf Hoe kan ik deze waarden omzetten naar rem, em of vw en vh? Ik snap dit nog niet zo heel goed.

**Comment by r20222** [comment]
Het is gelukt om het logo in rem waarden om te zetten. Ik heb de pixels gedeeld door 16px en kwam daarmee op de juiste rem waarden. Bedankt @Joost voor de uitleg van laatst.

```CSS
.Logo-ViniMini {
    width:8.875rem;
    height:6.25rem;
    margin-top:0.625rem;
}
```
