### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by joostf** [r20222/fix-the-flow-interactive-website#9]
```css

.logbook > article > button{
    border-top: 2px solid #72afa6;
    border-left:none;
    border-right:none;
    border-bottom:2px solid #72afa6;;
    background-color: white;
    display:flex;
    justify-content:flex-start;
    align-items: center;
    font-weight: 700;
    border-radius: 0px;
    color:var(--lichtblauw);
    letter-spacing: 2px;
    font-size: 24px;
    line-height: 22px;
    width:100%;
    text-align:left;
    padding: 40px 10px;
    transition-duration: 300ms;
    height:150px;
}

```

```css

.logbook div > ol > li > button{
    border-top: 2px solid #72afa6;
    border-left:none;
    border-right:2px solid var(--lichtblauw);
    border-bottom:none;
    background-color: white;
    font-weight: 700;
    border-radius: 0px;
    color:var(--lichtblauw);
    letter-spacing: 2px;
    font-size: 24px;
    line-height: 22px;
    width:15vw;
    /* width: 100px; */
    padding: 40px 10px;
    transition-duration: 300ms;
    height:100px;
    margin-left:0px;
}
```
